#!/bin/bash

while ps -ef | grep my_commit | grep -q -v grep; do
    sleep 1
done

while [ ! -f /tmp/vyos-config-status ]
do
  sleep 1
done

status=$(cat /tmp/vyos-config-status)

if [ $status -ne 0 ]; then
  echo "Configuration error"
else
  echo "Configuration success"
fi
