#!/bin/bash

# **** License ****
# Version: VPL 1.0
# 
# The contents of this file are subject to the Vyatta Public License
# Version 1.0 ("License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.vyatta.com/vpl
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
# the License for the specific language governing rights and limitations
# under the License.
# 
# This code was originally developed by Vyatta, Inc.
# Portions created by Vyatta are Copyright (C) 2006, 2007 Vyatta, Inc.
# All Rights Reserved.
# 
# Author: An-Cheng Huang
# Date: 2007
# Description: config notify script
# 
# **** End License ****

[ -r /etc/default/vyatta ] && source /etc/default/vyatta

declare cur_tty=$(ps -o tty= |head -n1)
declare cur_user=$(id -un)
declare -a ulist=( $(ps -a -o args,tty,ruser n \
                     | grep "^newgrp $VYATTA_CFG_GROUP_NAME" | cut -c 29-) )

for (( i = 0; i < ${#ulist[@]}; i += 2 )); do
  utty=${ulist[i]}
  if [ "$utty" == "$cur_tty" ]; then
    continue
  fi
  user=$(grep "[^:]\+:[^:]*:${ulist[i+1]}:" /etc/passwd | cut -d ':' -f 1)
  sudo write $user $utty <<EOF
Active configuration has been changed by user '$cur_user' on '$cur_tty'.
Please make sure you do not have conflicting changes. You can also discard
the current changes by issuing 'exit discard'.
EOF
done
