#!/bin/sh

# **** License ****
# Version: VPL 1.0
# 
# The contents of this file are subject to the Vyatta Public License
# Version 1.0 ("License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.vyatta.com/vpl
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
# the License for the specific language governing rights and limitations
# under the License.
# 
# This code was originally developed by Vyatta, Inc.
# Portions created by Vyatta are Copyright (C) 2006, 2007 Vyatta, Inc.
# All Rights Reserved.
# 
# Author: Stig Thormodsrud
# Date: 2007
# Description: dhcp client hook
# 
# **** End License ****

# To enable this script set the following variable to "yes"
RUN="yes"

if [ "$RUN" = "yes" ]; then
        LOG=/var/lib/dhcp3/dhclient_"$interface"_lease
        echo `date` > $LOG

        for i in reason interface new_expiry new_dhcp_lease_time medium \
                        alias_ip_address new_ip_address new_broadcast_address \
                        new_subnet_mask new_domain_name new_network_number \
                        new_domain_name_servers new_routers new_static_routes \
			new_dhcp_server_identifier new_dhcp_message_type \
                        old_ip_address old_subnet_mask old_domain_name \
                        old_domain_name_servers old_routers \
                        old_static_routes; do
                echo $i=\'${!i}\' >> $LOG
        done
fi
