#define VYOS_SUCCESS 0
#define VYOS_GENERAL_FAILURE 1
#define VYOS_INVALID_PATH 2
#define VYOS_EMPTY_CONFIG 3
#define VYOS_CONFIG_PARSE_ERROR 4
#define VYOS_COMMIT_FAILURE 5
#define VYOS_PARTIAL_COMMIT 6
